config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "sakes#index"
  get 'sakes/search'
  resources :users,only: [:show,:destroy]
  resources :sakes do
    resources :comments,only:[:create,:destroy]
    resource  :favorites,only:[:create,:destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '北海道' }, { id: 2, name: '東北' }, { id: 3, name: '関東' },
    { id: 4, name: '北陸' }, { id: 5, name: '中部' }, { id: 6, name: '東海' },
    { id: 7, name: '近畿' }, { id: 8, name: '中国' }, { id: 9, name: '四国' },
    { id: 10, name: '九州' }, { id: 11, name: 'その他' }
  ]
  
  include ActiveHash::Associations
  has_many :sakes
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :sake
end

app/models/easy.rb
class Easy < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '飲みやすい' },
    { id: 2, name: '普通' },
    { id: 3, name: 'クセがある' },
    { id: 4, name: 'クセがすごい' },
  ]

  include ActiveHash::Associations
  has_many :sakes
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :sake

  validates_uniqueness_of :sake_id, scope: :user_id
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '北海道' }, { id: 2, name: '青森県' }, { id: 3, name: '岩手県' },
    { id: 4, name: '宮城県' }, { id: 5, name: '秋田県' }, { id: 6, name: '山形県' },
    { id: 7, name: '福島県' }, { id: 8, name: '茨城県' }, { id: 9, name: '栃木県' },
    { id: 10, name: '群馬県' }, { id: 11, name: '埼玉県' }, { id: 12, name: '千葉県' },
    { id: 13, name: '東京都' }, { id: 14, name: '神奈川県' }, { id: 15, name: '新潟県' },
    { id: 16, name: '富山県' }, { id: 17, name: '石川県' }, { id: 18, name: '福井県' },
    { id: 19, name: '山梨県' }, { id: 20, name: '長野県' }, { id: 21, name: '岐阜県' },
    { id: 22, name: '静岡県' }, { id: 23, name: '愛知県' }, { id: 24, name: '三重県' },
    { id: 25, name: '滋賀県' }, { id: 26, name: '京都府' }, { id: 27, name: '大阪府' },
    { id: 28, name: '兵庫県' }, { id: 29, name: '奈良県' }, { id: 30, name: '和歌山県' },
    { id: 31, name: '鳥取県' }, { id: 32, name: '島根県' }, { id: 33, name: '岡山県' },
    { id: 34, name: '広島県' }, { id: 35, name: '山口県' }, { id: 36, name: '徳島県' },
    { id: 37, name: '香川県' }, { id: 38, name: '愛媛県' }, { id: 39, name: '高知県' },
    { id: 40, name: '福岡県' }, { id: 41, name: '佐賀県' }, { id: 42, name: '長崎県' },
    { id: 43, name: '熊本県' }, { id: 44, name: '大分県' }, { id: 45, name: '宮崎県' },
    { id: 46, name: '鹿児島県' }, { id: 47, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :sakes
end

app/models/sake.rb
class Sake < ApplicationRecord
  # -Association-
  belongs_to :user
  has_one_attached :image
  has_many :comments,     dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :area
  belongs_to :easy
  belongs_to :sourness
  belongs_to :taste
  belongs_to :total

  validates :name, presence:true

end

app/models/sourness.rb
class Sourness < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: 'ない' },
    { id: 2, name: '少ない' },
    { id: 3, name: '少しある' },
    { id: 4, name: '少し強い' },
    { id: 5, name: '強い' },
  ]

  include ActiveHash::Associations
  has_many :sakes
end

app/models/taste.rb
class Taste < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '超甘口' },
    { id: 2, name: '甘口' },
    { id: 3, name: 'やや甘口' },
    { id: 4, name: 'やや辛口' },
    { id: 5, name: '辛口' },
    { id: 6, name: '超辛口' },
  ]

  include ActiveHash::Associations
  has_many :sakes
end

app/models/total.rb
class Total < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '⭐️' },
    { id: 2, name: '⭐️⭐️' },
    { id: 3, name: '⭐️⭐️⭐️' },
    { id: 4, name: '⭐️⭐️⭐️⭐️' },
    { id: 5, name: '⭐️⭐️⭐️⭐️⭐️' },
  ]

  include ActiveHash::Associations
  has_many :sakes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # -Association-
  has_many :sakes
  has_many :comments,  dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :icon

  validates :nickname, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname,:icon])

      devise_parameter_sanitizer.permit(:account_update, keys: [:nickname,:icon])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create 
    comment = Comment.new(comment_params)
    if comment.save
      redirect_to "/sakes/#{comment.sake.id}"
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id],sake_id: params[:sake_id])
    if @comment.destroy
      redirect_to "/sakes/#{@comment.sake_id}"
    end
  end


  private
    def comment_params
      params.require(:comment).permit(:text).merge(user_id: current_user.id, sake_id: params[:sake_id])
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create 
    @sake = Sake.find(params[:sake_id])
    favorite = Favorite.create(user_id: current_user.id, sake_id: params[:sake_id])
    render 'btn-fav.js.erb'
  end

  def destroy
    @sake = Sake.find(params[:sake_id])
    @favorite = Favorite.find_by(user_id:current_user.id, sake_id:params[:sake_id])
    @favorite.destroy
    render 'btn-fav.js.erb'
  end
end

app/controllers/sakes_controller.rb
class SakesController < ApplicationController 
  before_action :authenticate_user!, except:[:index,:show]
  before_action :sake_set, only: [:edit, :show, :update, :destroy]
  before_action :unmach_user, only: [:edit,:update,:destroy]


  def index
    @q = Sake.ransack(params[:q])
    @sakes = @q.result(distinct: true).order(id: "DESC").page(params[:page]).per(12)
    @name = Sake.select("name").distinct
    @category = Sake.select("category").distinct
    @sake_rank = Sake.find(Favorite.group(:sake_id).order('count(sake_id) desc').limit(10).pluck(:sake_id))
    @user_rank = User.find(Sake.group(:user_id).order('count(user_id) desc').limit(5).pluck(:user_id))
  end

  def search
    index
    render:index
  end


  def new
    @sake = Sake.new
  end

  def create
    @sake = Sake.new(sake_params)
    if @sake.valid?
      @sake.save
      redirect_to user_path(current_user.id)
    else
      render :new
    end
  end

  def show
    @q = Sake.ransack(params[:q])
    @comment = Comment.new
    @comments = @sake.comments.includes(:user)
    @similar = Sake.where(taste_id:@sake.taste_id,sourness_id:@sake.sourness_id,easy_id:@sake.easy_id).where.not(taste_id:0).where.not(id:@sake.id)
  end

  def edit
  end

  def update
    if @sake.update(sake_params)
      redirect_to sake_path(@sake.id)
    else
      render :edit
    end
  end

  def destroy
    if @sake.destroy
      redirect_to user_path(current_user.id)
    end
  end

  private
  def sake_params
    params.require(:sake).permit(:name, :category, :total_id, :taste_id, :sourness_id, :easy_id, :place, :impression, :maker, :area_id, :text, :image).merge(user_id:current_user.id)
  end

  def sake_set
    @sake = Sake.find(params[:id])
  end

  def unmach_user
    unless current_user.id == @sake.user_id
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])

    @sakes = Sake.includes(:user).where(user_id:@user.id).order(id: "DESC") #ユーザーの投稿した酒の一覧
    @sakes_paged = @sakes.page(params[:page]).per(9)#ページネーションしたもの
    @complete = @sakes.where.not(name:"",impression:"",maker:"",text:"",category:"",total_id:0,taste_id:0,sourness_id:0,easy_id:0,place:"",area_id:0)#自分の投稿のうち、項目が埋まっているもの

    favorite_id = Favorite.where(user_id: @user.id).pluck(:sake_id)  #ユーザーのお気に入りのsake_idカラムを取得
    @favorites = Sake.find(favorite_id) #ユーザーのお気に入り登録した酒の一覧
  end

  def destroy
    if current_user.destroy
      redirect_to root_path
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sakes_helper.rb
module SakesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/favorites/btn-fav.js.erb
var fav = document.getElementById("btn-fav<%=@sake.id%>");
fav.innerHTML = ("<%= escape_javascript(render('shared/btn-fav',sake:@sake)) %>");

app/views/sakes/index.html.erb
<%= render "shared/header"%>
<main>
  <div class="album py-5 bg-light">
    <div class="d-flex justify-content-between px-5",id="title">
      <h2>〜みんなの酒メモ〜</h2>
      <%# 検索バー %>
        <%= search_form_for @q, url: sakes_search_path,class:"my-auto text-body" do |f| %>
          <div class="d-flex">
          <div class="ml-2 my-auto"><%= sort_link(@q, :created_at, "登録日")%></div>
          <div class="ml-2 my-auto"><%= sort_link(@q, :name, "名前:")%></div>
          <%= f.collection_select :name_cont, @name, :name, :name, include_blank: '指定なし'%>
          <div class="ml-2 my-auto"><%= sort_link(@q, :category, "種類:")%></div>
          <%= f.collection_select :category_eq, @category, :category, :category, include_blank: '指定なし'%>
          <div class="ml-2 my-auto"> <%= sort_link(@q, :total_id, "評価:")%></div>
          <%= f.collection_select :total_id_eq, Total.all, :id, :name, include_blank: '指定なし'%>
          <div class="ml-2 my-auto"><%= f.submit "絞り込む",class:"ml-2" %></div>
          </div>
        <% end %>
      <%# /検索バー %>
    </div><%# /id:title %>
    <div class="container ",id="lists">
      <div class="d-flex flex-wrap">
        <% @sakes.each do |sake| %>
            <!--card内枠-->
            <li class="col-3 shadow-sm my-1 list-group-item"> 
              <!--card上部-->
              <%if sake.image.attached?%>
                <%=link_to(sake_path(sake.id))do%>
                  <%= image_tag sake.image, size:'200x200',class:'card-img-top object-fit-cover'%>
                <%end%>
              <%else%>
                <%=link_to(sake_path(sake.id))do%>
                  <%= image_tag 'no-image.png', size:'200x200', class: 'card-img-top object-fit-cover'%> 
                <%end%>
              <%end%>
              <%=link_to(sake_path(sake.id),class:"text-body")do%><!--酒の名前-->
                <h3 class="overflow-hidden h-2 mt-2"><%= sake.name %></h3>
              <%end%>
              <!--/card上部-->
              <!--card下部-->
              <div class="container">
                <p class="font-s"><!--酒情報-->
                    　　種類:<%= sake.category %><br>
                    総合評価:<%= sake.total.name %>
                </p>

                <div class="btn-group d-flex justify-content-between h-3">
                  <%=link_to sake.user.nickname,user_path(sake.user_id),class:"col-7 text-body"%><!--ユーザー名-->
                  <%= render partial:'shared/btn-fav', locals:{sake:sake}%><!--お気に入りボタン-->
                </div>

              </div>
              <!--/card下部-->
            </li>
            <!--/card内枠-->
        <%end%>
      </div>
         <div class="d-flex justify-content-center"><%= paginate @sakes%></div><!--ページ切り替えボタン-->
    </div><!--id:lists-->

    <%# いいねランキング表示 %>
    <div class="container">
      <h2>〜いいねランキング〜</h2>
    </div>
    <div class="container d-flex scroll-x",id="lists">
      <%@sake_rank.each.with_index(1) do|sake,i|%>
        <li class="col-3 shadow-sm my-1 list-group-item "> 
          <!--card上部-->
          <%if sake.image.attached?%>
            <%=link_to(sake_path(sake.id))do%>
              <%= image_tag sake.image, size:'200x200',class:'card-img-top object-fit-cover'%>
            <%end%>
          <%else%>
            <%=link_to(sake_path(sake.id))do%>
              <%= image_tag 'no-image.png', size:'200x200', class: 'card-img-top object-fit-cover'%> 
            <%end%>
          <%end%>
          <div class="d-flex justify-content-between mt-1">
            <%=link_to(sake_path(sake.id),class:"text-body")do%>
               <% if i == 1%>
                <div>🥇第<%=i%>位</div>
              <%elsif i == 2%>
                <div>🥈第<%=i%>位</div>
              <%elsif i == 3%>
                <div>🥉第<%=i%>位</div>
              <%else%>
                <div>第<%=i%>位</div>
              <%end%>
              <h3 class="overflow-hidden my-auto "><%= sake.name %></h3>
            <%end%>
            <%= render partial:'shared/btn-fav', locals:{sake:sake}%><!--お気に入りボタン-->
          </div>
        </li>
      <%end%>
    </div>
    <%# /いいねランキング表示 %>

     <%# ユーザーランキング表示 %>
    <div class="container mt-5">
      <h2>〜投稿数ランキング〜</h2>
    </div>
    <div class="container d-flex scroll-x",id="lists">
      <%@user_rank.each.with_index(1) do|user,i|%>
        <li class="col-3 shadow-sm py-3 my-1 list-group-item"> 
          <%=link_to(user_path(user.id),class:"text-body")do%>
            <% if i == 1%>
              <div>🥇第<%=i%>位</div>
            <%elsif i == 2%>
              <div>🥈第<%=i%>位</div>
            <%elsif i == 3%>
              <div>🥉第<%=i%>位</div>
            <%else%>
              <div>第<%=i%>位</div>
            <%end%>
            <div class="d-flex">
              <%if user.icon.attached?%>
                <%=image_tag user.icon,size:'60x60',class:"object-fit-cover rounded-circle mr-3"%>
              <%else%>
                <%=image_tag 'no-icon.png',size:'60x60',class:"object-fit-cover rounded-circle mr-3 border"%>
              <%end%>
              <div>
                <h3 class="my-auto"><%= user.nickname %></h3>
                投稿:<%=user.sakes.length%>
              </div>
            </div>
          <%end%>
        </li>
      <%end%>  
    </div>
    <%# /ユーザーランキング表示 %>
  </div><!-- /album py-5 bg-light -->
</main>
<%= render "shared/footer"%>

app/views/sakes/show.html.erb
<%= render 'shared/header'%>

<div class="container mt-5 d-flex"><!--上部-->
  <div class="col-5"><!--上部左-->
    <h2 class="pt-3 text-center ml-3 border-bottom"> <%=@sake.name%> </h2>
    <div class="container my-4 ">
      <p class="col">　　　種類 :<%=@sake.category%></p>
      <p class="col">　　酒蔵名 :<%=@sake.maker%></p>
      <p class="col">　　製造地 :<%=@sake.area.name%></p>
      <h4 class="my-3 border-top pt-2"><%=link_to @sake.user.nickname,user_path(@sake.user_id),class:"text-body"%>の評価:<%=@sake.total.name%></h4>
      <p class="col">　のみくち : <%=@sake.taste.name%></p>
      <p class="col">　　　酸味 : <%=@sake.sourness.name%></p>
      <p class="col">飲みやすさ : <%=@sake.easy.name%></p>
      <p class="col">飲んだ場所 : <%=@sake.place%></p>
      <h4 class="my-3 border-top pt-2"><%=link_to @sake.user.nickname,user_path(@sake.user_id),class:"text-body"%>の感想</h4>
      <p class="card w-100 font-s text-body border rounded h-min-5 p-1"><%=@sake.impression%><p>
      <%if user_signed_in? && current_user.id == @sake.user.id%>
        <div class="my-2">
        <%= link_to '編集', edit_sake_path(@sake.id), class: "btn btn-sm btn-outline-secondary my-auto"%>
        <%= link_to '削除', sake_path(@sake.id),method: :delete, class: "btn btn-sm btn-outline-secondary my-auto"%>
        </div>
      <%else%>
      <%= render partial:'shared/btn-fav', locals:{sake:@sake}%><!--お気に入りボタン-->
      <%end%>
    </div>
  </div><!--上部左-->
  <div class="col"><!--上部右-->
    <%if user_signed_in? && @sake.image.attached?%>
      <%= image_tag @sake.image, class: 'object-fit-contain w-100 h-26'%>
    <%else%>
      <%= image_tag 'no-image.png', class: 'object-fit-contain w-100 h-26'%>
    <%end%>
      <p class="container mt-2 mr-2 border rounded h-min-9 p-1"><%=@sake.text %><p>
  </div>
</div><!--上部-->

<%# コメント機能 %>
<div class="container mb-3">
  <div class="col">
    <h2>コメント</h2>
    <%# コメント投稿機能 %>
    <div class="container mb-2">
      <% if user_signed_in?%> 
        <%= form_with model: [@sake,@comment], local: true, class:"d-flex" do |f| %>
          <%= f.text_area :text,class:"form-control text-body w-75", placeholder:"相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。",row:2%>
          <%= f.submit "コメントする", class:"mt-2 btn btn-primary m-auto" %>
        <% end %>
      <% else %>
        <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
      <% end %>
    </div>
    <%# /コメント投稿機能 %>
    <%# コメント一覧表示 %>
    <div class="col">
      <h4 class = "">＜コメント一覧＞</h4>
      <div class="container mt-2">
        <%if @comments.present?%>
         <% @comments.reverse_each do |comment| %>
            <li class="container d-flex border rounded">
              <p class="my-auto"><%= comment.user.nickname %>:</p>
              <p class="col my-auto"><%= comment.text %></p>
              <p class="text-black-50 my-auto font-xs text-right"><%= comment.created_at%></p>
              <% if user_signed_in? && (comment.user_id == current_user.id || @sake.user_id == current_user.id)%>
                <%= link_to '削除', sake_comment_path(comment.sake_id, comment.id),method: :delete, class: "btn btn-sm btn-outline-secondary my-2"%>
              <% end %>
            </li>
          <% end %>
        <%else%>
          <p>※コメントはありません※</p>
        <%end%>
      </div>
    </div>
    <%# /コメント一覧表示 %>
  </div>
</div>
<%# /コメント %>

 <%# 似ている酒表示 %>
 <%if @similar.any?%>
  <div class="container">
    <h3>似ているお酒</h3>
  </div>
  <div class="container d-flex scroll-x",id="lists">
    <%@similar.each do|sake,i|%>
      <li class="col-3 shadow-sm my-1 list-group-item ">
        <!--card上部-->
        <%if sake.image.attached?%>
          <%=link_to(sake_path(sake.id))do%>
            <%= image_tag sake.image, size:'200x200',class:'card-img-top object-fit-cover'%>
          <%end%>
        <%else%>
          <%=link_to(sake_path(sake.id))do%>
            <%= image_tag 'no-image.png', size:'200x200', class: 'card-img-top object-fit-cover'%> 
          <%end%>
        <%end%>
        <div>
          <div class="d-flex justify-content-between">
            <%=link_to(sake_path(sake.id),class:"text-body")do%>
              <h3 class="my-auto"><%= sake.name %></h3>
            <%end%>
            <%= render partial:'shared/btn-fav', locals:{sake:@sake}%><!--お気に入りボタン-->
          </div>
          <div class="font-xs">
            のみくち　: <%=sake.taste.name%><br>
            　酸味　　: <%=sake.sourness.name%><br>
            飲みやすさ: <%=sake.easy.name%><br>
          </div>
        </div>
      </li>
    <%end%>
  </div>
<%end%>
<%# /似ている酒表示 %>

app/views/users/show.html.erb
<%= render "shared/bar"%>
<main>
  <div class="album py-5 bg-light">
    <div class="container",id="title">
      <h2>〜
      <%if @user.icon.attached?%>
        <%=image_tag @user.icon,size:'60x60',class:"object-fit-cover rounded-circle"%>
      <%else%>
        <%=image_tag 'no-icon.png',size:'60x60',class:"object-fit-cover rounded-circle border"%>
      <%end%>
      <%= @user.nickname %>の酒図鑑〜</h2>
      <p class="text-bottom">
        見つけた数:<%=@sakes.length%>　調べた数:<%=@complete.length%>
        <%if user_signed_in? && @user.id == current_user.id%>
          <%unless @sakes.length == @complete.length %>
          <span class="mx-2 text-danger font-xs ">未完成のメモがあるようです。調べて完成させましょう。</span>
          <%else%>
          <span class="mx-2 text-body font-xs ">新しい酒を探しましょう！</span>
          <%end%>
        <%end%>
      </p>
    </div><%# /id:title %>

    <div class="container",id="lists"><!--自分の投稿一覧-->
      <div class="d-flex flex-wrap">
       <% @sakes_paged.each do |sake| %>
          <%if user_signed_in? && current_user.id == sake.user_id%>
            <%if @complete.include?(sake) && sake.image.attached?%><!---->
              <li class="col-4 shadow-sm my-1 list-group-item border-light">
            <%else%>  
              <li class="col-4 shadow-sm my-1 list-group-item border-light bg-danger">
            <%end%>
          <%else%>
            <li class="col-4 shadow-sm py-3 my-1 list-group-item border-light">
          <%end%>
            <div class="card shadow-sm pb-3 pt-1 mt-2"> <!--card内枠-->
                  <div class="font-xxs ml-auto"><%=sake.created_at%></div>
              <%if sake.image.attached?%>
                <%=link_to(sake_path(sake.id))do%>
                  <%= image_tag sake.image, size:'326x326',class:'card-img-top object-fit-cover'%>
                <%end%>
              <%else%>
                <%=link_to(sake_path(sake.id))do%>
                  <%= image_tag 'no-image.png', size:'326x326',class: 'card-img-top object-fit-cover'%> 
                <%end%> 
              <%end%>
              <div class="container">
                <div class="card-text mt-2 px-2 d-flex justify-content-between">
                  <%=link_to(sake_path(sake.id))do%>
                    <h3 class="overflow-hidden text-body h-4 mt-2"><%= sake.name %></h3>
                  <%end%>
                </div>
                <div class="font-s d-flex justify-content-between">
                  <div>
                    　　種類:<%= sake.category %><br>
                    総合評価:<%= sake.total.name %>
                  </div>
                  <div class="font-xl text-danger text-right">❤️ <%=sake.favorites.length%></div>
                </div>
                  <div class="border font-xs rounded h-3 w-100 mt-2 px-1 overflow-hidden"> <%= sake.impression%></div>
                <div class="btn-group d-flex justify-content-between pt-1">
                  <% if user_signed_in? && sake.user_id == current_user.id %>
                    <%= link_to '編集', edit_sake_path(sake.id), class: "btn btn-sm btn-outline-secondary" %>
                    <%= link_to '削除', sake_path(sake.id),method: :delete, class: "btn btn-sm btn-outline-secondary"%>
                  <% end %>
                </div>
              </div><!--card-body-->
                <%if user_signed_in?%>
                  <% unless @complete.include?(sake) || sake.user_id != current_user.id%>
                    <div class="mt-2 text-center text-danger font-xxs ">未登録の項目があります</div>
                  <% end %>
                <%end%>
            </div><!--card内枠-->
          </li>
        <%end%>
      </div>
      <div class="d-flex justify-content-center"><%= paginate @sakes_paged%></div>
    </div><!--/自分の投稿一覧-->

    <div class="container mt-5",id="favorite"><!--お気に入り表示-->

      <div class="container",id="title">
        <h2>〜お気に入り一覧〜　 <span class="font-m"><%=@favorites.length%>件</span></h2>
      </div><%# /id:title %>

      <div class="d-flex scroll-x"><!--お気に入り一覧-->
        <% @favorites.reverse_each do |sake| %>
            <!--card内枠-->
            <li class="col-4 shadow-sm py-3 scroll-item my-1 list-group-item"> 
            
              <!--card上部-->
              <%if sake.image.attached?%>
                <%=link_to(sake_path(sake.id))do%>
                  <%= image_tag sake.image, size:'326x326',class:'card-img-top object-fit-cover'%>
                <%end%>
              <%else%>
                <%=link_to(sake_path(sake.id))do%>
                  <%= image_tag 'no-image.png', size:'326x326',class: 'card-img-top object-fit-cover '%> 
                <%end%>
              <%end%>
              <!--/card上部-->
              <!--card下部-->
              <div class="container">
                <div class="card-text mt-2 d-flex justify-content-between">
                  <%=link_to(sake_path(sake.id))do%>
                    <h3 class="overflow-hidden text-body h-4 mt-2"><%= sake.name %></h3>
                  <%end%>
                  <div class="font-xl text-danger text-right">❤️ <%=sake.favorites.length%></div>
                </div>
                <p class="font-s">
                    　　種類:<%= sake.category %><br>
                    総合評価:<%= sake.total.name %>
                </p>
                <div class="btn-group d-flex justify-content-between h-3">
                  <%=link_to sake.user.nickname,"/users/#{sake.user_id}",class:"col-7 text-body"%><!--ユーザー名-->
                  <%if user_signed_in? && current_user.id == @user.id %>
                      <%= link_to 'リストから削除', sake_favorites_path(sake),method: :delete, class: "rounded-pill border text-dark my-auto w-100 ml-2"%> <!--いいねボタンOFF-->
                  <%end%>
                </div>
              </div>
              <!--/card下部-->
            </li>
            <!--/card内枠-->
        <%end%>
      </div><!--/お気に入り一覧-->
    </div><!--/お気に入り表示-->
  </div><!-- /album py-5 bg-light -->
</main>
<%= render "shared/footer"%>