config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "sakes#index"
  get 'sakes/search'
  resources :users,only: [:show,:destroy]
  resources :sakes do
    resources :comments,only:[:create,:destroy]
    resource  :favorites,only:[:create,:destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '北海道' }, { id: 2, name: '東北' }, { id: 3, name: '関東' },
    { id: 4, name: '北陸' }, { id: 5, name: '中部' }, { id: 6, name: '東海' },
    { id: 7, name: '近畿' }, { id: 8, name: '中国' }, { id: 9, name: '四国' },
    { id: 10, name: '九州' }, { id: 11, name: 'その他' }
  ]
  
  include ActiveHash::Associations
  has_many :sakes
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :sake
end

app/models/easy.rb
class Easy < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '飲みやすい' },
    { id: 2, name: '普通' },
    { id: 3, name: 'クセがある' },
    { id: 4, name: 'クセがすごい' },
  ]

  include ActiveHash::Associations
  has_many :sakes
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :sake

  validates_uniqueness_of :sake_id, scope: :user_id
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '北海道' }, { id: 2, name: '青森県' }, { id: 3, name: '岩手県' },
    { id: 4, name: '宮城県' }, { id: 5, name: '秋田県' }, { id: 6, name: '山形県' },
    { id: 7, name: '福島県' }, { id: 8, name: '茨城県' }, { id: 9, name: '栃木県' },
    { id: 10, name: '群馬県' }, { id: 11, name: '埼玉県' }, { id: 12, name: '千葉県' },
    { id: 13, name: '東京都' }, { id: 14, name: '神奈川県' }, { id: 15, name: '新潟県' },
    { id: 16, name: '富山県' }, { id: 17, name: '石川県' }, { id: 18, name: '福井県' },
    { id: 19, name: '山梨県' }, { id: 20, name: '長野県' }, { id: 21, name: '岐阜県' },
    { id: 22, name: '静岡県' }, { id: 23, name: '愛知県' }, { id: 24, name: '三重県' },
    { id: 25, name: '滋賀県' }, { id: 26, name: '京都府' }, { id: 27, name: '大阪府' },
    { id: 28, name: '兵庫県' }, { id: 29, name: '奈良県' }, { id: 30, name: '和歌山県' },
    { id: 31, name: '鳥取県' }, { id: 32, name: '島根県' }, { id: 33, name: '岡山県' },
    { id: 34, name: '広島県' }, { id: 35, name: '山口県' }, { id: 36, name: '徳島県' },
    { id: 37, name: '香川県' }, { id: 38, name: '愛媛県' }, { id: 39, name: '高知県' },
    { id: 40, name: '福岡県' }, { id: 41, name: '佐賀県' }, { id: 42, name: '長崎県' },
    { id: 43, name: '熊本県' }, { id: 44, name: '大分県' }, { id: 45, name: '宮崎県' },
    { id: 46, name: '鹿児島県' }, { id: 47, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :sakes
end

app/models/sake.rb
class Sake < ApplicationRecord
  # -Association-
  belongs_to :user
  has_one_attached :image
  has_many :comments,     dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :area
  belongs_to :easy
  belongs_to :sourness
  belongs_to :taste
  belongs_to :total

  validates :name, presence:true

end

app/models/sourness.rb
class Sourness < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: 'ない' },
    { id: 2, name: '少ない' },
    { id: 3, name: '少しある' },
    { id: 4, name: '少し強い' },
    { id: 5, name: '強い' },
  ]

  include ActiveHash::Associations
  has_many :sakes
end

app/models/taste.rb
class Taste < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '超甘口' },
    { id: 2, name: '甘口' },
    { id: 3, name: 'やや甘口' },
    { id: 4, name: 'やや辛口' },
    { id: 5, name: '辛口' },
    { id: 6, name: '超辛口' },
  ]

  include ActiveHash::Associations
  has_many :sakes
end

app/models/total.rb
class Total < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '⭐️' },
    { id: 2, name: '⭐️⭐️' },
    { id: 3, name: '⭐️⭐️⭐️' },
    { id: 4, name: '⭐️⭐️⭐️⭐️' },
    { id: 5, name: '⭐️⭐️⭐️⭐️⭐️' },
  ]

  include ActiveHash::Associations
  has_many :sakes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # -Association-
  has_many :sakes
  has_many :comments,  dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :icon

  validates :nickname, presence:true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create 
    comment = Comment.new(comment_params)
    if comment.save
      redirect_to "/sakes/#{comment.sake.id}"
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id],sake_id: params[:sake_id])
    if @comment.destroy
      redirect_to "/sakes/#{@comment.sake_id}"
    end
  end


  private
    def comment_params
      params.require(:comment).permit(:text).merge(user_id: current_user.id, sake_id: params[:sake_id])
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create 
    @sake = Sake.find(params[:sake_id])
    favorite = Favorite.create(user_id: current_user.id, sake_id: params[:sake_id])
    render 'btn-fav.js.erb'
  end

  def destroy
    @sake = Sake.find(params[:sake_id])
    @favorite = Favorite.find_by(user_id:current_user.id, sake_id:params[:sake_id])
    @favorite.destroy
    render 'btn-fav.js.erb'
  end
end

app/controllers/sakes_controller.rb
class SakesController < ApplicationController 
  before_action :authenticate_user!, except:[:index,:show]
  before_action :sake_set, only: [:edit, :show, :update, :destroy]
  before_action :unmach_user, only: [:edit,:update,:destroy]


  def index
    @q = Sake.ransack(params[:q])
    @sakes = @q.result(distinct: true).order(id: "DESC").page(params[:page]).per(12)
    @name = Sake.select("name").distinct
    @category = Sake.select("category").distinct
    @sake_rank = Sake.find(Favorite.group(:sake_id).order('count(sake_id) desc').limit(10).pluck(:sake_id))
    @user_rank = User.find(Sake.group(:user_id).order('count(user_id) desc').limit(5).pluck(:user_id))
  end

  def search
    index
    render:index
  end


  def new
    @sake = Sake.new
  end

  def create
    @sake = Sake.new(sake_params)
    if @sake.valid?
      @sake.save
      redirect_to user_path(current_user.id)
    else
      render :new
    end
  end

  def show
    @q = Sake.ransack(params[:q])
    @comment = Comment.new
    @comments = @sake.comments.includes(:user)
    @similar = Sake.where(taste_id:@sake.taste_id,sourness_id:@sake.sourness_id,easy_id:@sake.easy_id).where.not(taste_id:0).where.not(id:@sake.id)
  end

  def edit
  end

  def update
    if @sake.update(sake_params)
      redirect_to sake_path(@sake.id)
    else
      render :edit
    end
  end

  def destroy
    if @sake.destroy
      redirect_to user_path(current_user.id)
    end
  end

  private
  def sake_params
    params.require(:sake).permit(:name, :category, :total_id, :taste_id, :sourness_id, :easy_id, :place, :impression, :maker, :area_id, :text, :image).merge(user_id:current_user.id)
  end

  def sake_set
    @sake = Sake.find(params[:id])
  end

  def unmach_user
    unless current_user.id == @sake.user_id
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])

    @sakes = Sake.includes(:user).where(user_id:@user.id).order(id: "DESC") #ユーザーの投稿した酒の一覧
    @sakes_paged = @sakes.page(params[:page]).per(9)#ページネーションしたもの
    @complete = @sakes.where.not(name:"",impression:"",maker:"",text:"",category:"",total_id:0,taste_id:0,sourness_id:0,easy_id:0,place:"",area_id:0)#自分の投稿のうち、項目が埋まっているもの

    favorite_id = Favorite.where(user_id: @user.id).pluck(:sake_id)  #ユーザーのお気に入りのsake_idカラムを取得
    @favorites = Sake.find(favorite_id) #ユーザーのお気に入り登録した酒の一覧
  end

  def destroy
    if current_user.destroy
      redirect_to root_path
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sakes_helper.rb
module SakesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head lang="ja">
    <title>SakeZukan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_bar.erb
<header>
  <div class="d-flex justify-content-between border-bottom" style="background-image('header.png')">
    <div class="d-flex">
      <%= link_to(root_path, class: 'd-flex justify-content-center align-items-center text-body ml-3') do %>
        <%= image_tag 'title-logo.png' , size: '185x50' , class:"img-fluid"%>
      <% end %>
    </div>
    <div class="d-flex item-center my-auto mr-3">
    <% if user_signed_in?%>
      <%= link_to "新しい酒を見つけた！",new_sake_path,class:"btn btn-success my-2 mx-3"%>
      <%= link_to "マイページ", "/users/#{current_user.id}", class: "btn btn-primary my-2 mx-3",id: "user-nickname" %>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-secondary my-2 mx-3" %>
    <% else %>
      <%= link_to 'ログイン', new_user_session_path, class: "btn btn-primary my-2 mx-3" %>
      <%= link_to '新規登録', new_user_registration_path, class: "btn btn-success my-2 mx-3" %>
    <% end %>
    </div>
  </div>
</header>

app/views/shared/_btn-fav.html.erb
<div id="btn-fav<%=sake.id%>">
  <%if user_signed_in? && current_user.id != sake.user_id %>
    <%unless Favorite.exists?(user_id:current_user.id,sake_id:sake.id) %>
      <%= link_to "♡ #{sake.favorites.length}",sake_favorites_path(sake),method: :post, class: "btn font-xl text-danger border border-danger rounded-pill my-auto",remote: true %><!--いいね未-->
    <%else%>
      <%= link_to "❤️ #{sake.favorites.length}", sake_favorites_path(sake),method: :delete, class: "btn font-xl text-light border border-light rounded-pill bg-danger my-auto",remote: true %><!--いいね済-->
    <% end %>
  <%else%>
    <div class="font-xl text-danger my-auto">❤️ <%=sake.favorites.length%></div>
  <%end%>
</div>

app/views/shared/_footer.html.erb
<footer>
  <div class="d-flex justify-contnt-end">
    <%if user_signed_in?%>
      <%= link_to "ユーザー情報編集",edit_user_registration_path(current_user.id),class:"btn text-dark border ml-auto"%>
      <%= link_to "退会する","#",class:"btn text-dark border"%>
    <%end%>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <%= link_to image_tag("header.png", class:"w-100"), root_path %>　<%#最上段画像%>
  <%= link_to(root_path, class: 'd-flex justify-content-center align-items-center text-body') do %> <%#上段ロゴ＆タイトル%>
    <%= image_tag 'title-logo.png' , size: '185x50' , class:"img-fluid"%>
    <h1 class="text-body">僕の私の酒図鑑</h1>
  <% end %>
  <p class="text-muted text-center mt-2">　<%#中段テキスト%>
    <% if user_signed_in?%>
      こんにちは<%=current_user.nickname%>さん。最近美味しいお酒との出会いはありましたか？<br>忘れないうちにメモしておきましょう
    <%else%>
      飲んだことある気がする、飲んでみたら味わったか覚えてない…<br>そんな経験はありますか？飲んで調べて自分だけの酒図鑑を完成させましょう。<br>これで安心ですね。
    <%end%>
  </p>
  <div class="d-flex justify-content-between item-center my-auto border-bottom"> <%#下段ボタン群%>
    <%= search_form_for @q, url: sakes_search_path, class:"d-flex my-auto ml-3 h-2" do |f| %>
      <%if user_signed_in?%>
        <%if current_user.icon.attached?%>
          <%=image_tag current_user.icon,size:'40x40',class:"object-fit-cover rounded-circle mr-2"%>
        <%else%>
          <%=image_tag 'no-icon.png',size:'40x40',class:"object-fit-cover rounded-circle mr-2 border"%>
        <%end%>
      <%end%>
      <%= f.label :name_or_impression_or_text, "キーワード検索:",class:"my-auto mr-2"%>
      <%= f.search_field :name_or_impression_or_text_cont %>
      <%= f.submit "検索" ,class:"ml-2"%>
    <% end %>
    <div class="d-flex item-center my-auto mr-3">
    <% if user_signed_in?%>
      <%= link_to "新しい酒を見つけた！",new_sake_path,class:"btn btn-success my-2 mx-3"%>
      <%= link_to edit_user_registration_path do%>
      <%end%>
      <%= link_to "マイページ", "/users/#{current_user.id}", class: "btn btn-primary my-2 mx-3",id: "user-nickname" %>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-secondary my-2 mx-3" %>
    <% else %>
      <%= link_to 'ログイン', new_user_session_path, class: "btn btn-primary my-2 mx-3" %>
      <%= link_to '新規登録', new_user_registration_path, class: "btn btn-success my-2 mx-3" %>
    <% end %>
    </div>
  </div>
</header>